version: '3.8'

networks:
  mynet:
    external:
      name: mynet

services:
  webapinotes:
    container_name: webapinotes
    depends_on:
      - "postgers"
    networks:
      - mynet
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "62305:80"
      # - "9090:80"
    expose:
      - "80"
    environment:
      DB_CONNECTION_STRING: "Host=postgers;Port=5432;Database=Notes;Username=postgres;Password=159753"


  postgers:
    image: postgres
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "159753"
      POSTGRES_DB: "Notes"
